# Generated by Django 4.0.3 on 2023-05-07 23:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clienta',
            fields=[
                ('cod_clienta', models.AutoField(primary_key=True, serialize=False)),
                ('rut_clienta', models.BigIntegerField(unique=True)),
                ('dv_clienta', models.CharField(max_length=1)),
                ('tipo_clienta', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('tel', models.BigIntegerField()),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=10, null=True)),
                ('giro', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'clienta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('cod_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruccion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'detalle_preparacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('costo_unit', models.BigIntegerField(validators=[api.models.validar_positivo])),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('cod_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ft',
            fields=[
                ('cod_ft', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ft', models.CharField(max_length=100)),
                ('rendimiento', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('costo_tot', models.BigIntegerField()),
                ('img_ft', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_art', models.AutoField(primary_key=True, serialize=False)),
                ('nom_art', models.CharField(max_length=100)),
                ('tot_entradas', models.IntegerField(default=0)),
                ('tot_salidas', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('costo_art', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('cod_item', models.AutoField(primary_key=True, serialize=False)),
                ('nom_item', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(max_length=30)),
                ('cant_item', models.IntegerField(validators=[api.models.validar_positivo])),
                ('costo_std', models.BigIntegerField(validators=[api.models.validar_positivo])),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cod_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('cod_alfa_3', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=30)),
                ('valor_param', models.IntegerField(validators=[api.models.validar_positivo])),
            ],
            options={
                'db_table': 'parametro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('fecha_compromiso', models.DateField()),
                ('costo_tot', models.BigIntegerField()),
                ('margen', models.IntegerField()),
                ('precio', models.BigIntegerField()),
                ('fecha_entrega', models.DateField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('cod_perfil', models.SmallAutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=50)),
                ('mod1_acceso', models.IntegerField()),
                ('mod2_acceso', models.IntegerField()),
                ('mod3_acceso', models.IntegerField()),
                ('mod4_acceso', models.IntegerField()),
                ('mod5_acceso', models.IntegerField()),
                ('mod6_acceso', models.IntegerField()),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedora',
            fields=[
                ('cod_proveedora', models.AutoField(primary_key=True, serialize=False)),
                ('nom_proveedora', models.CharField(max_length=100, unique=True)),
                ('nom_contacto', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('tel', models.BigIntegerField()),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'proveedora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('cod_region', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepLegal',
            fields=[
                ('cod_rep_legal', models.AutoField(primary_key=True, serialize=False)),
                ('rut_rep_legal', models.BigIntegerField(unique=True)),
                ('dv_rep_legal', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('tel', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rep_legal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(validators=[api.models.validar_positivo])),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('cod_unidad', models.IntegerField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuaria',
            fields=[
                ('id_usuaria', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('logueada', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'usuaria',
                'managed': False,
            },
        ),
    ]
